version: '3.8'

services:
  aidan-mackey-net:
    image: aidan-mackey-net:latest
    container_name: aidan-mackey-net
    restart: unless-stopped
    ports:
      - "443:3000"
    networks:
      - monitoring

  ray-casting:
    image: aidanmackey/ray-casting
    container_name: ray-casting 
    restart: unless-stopped
    ports:
      - "3000:8080"
    networks:
      - monitoring
    depends_on:
      - aidan-mackey-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - "/mnt/shared/.logs/prometheus-aidan-mackey-net:/prometheus"
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    depends_on:
      - aidan-mackey-net
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"

networks:
  monitoring:
    external: true
