services:
  website-prod:
    image: aidan-mackey-net-prod
    container_name: aidan-mackey-net-prod
    restart: always
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV=${STAGE}
    volumes:
      - ../logs:/app/logs
    networks:
      - website

networks:
  website:
    driver: bridge
