services:
  aidan-mackey-net:
    image: aidan-mackey-net:latest
    container_name: aidan-mackey-net
    restart: unless-stopped
    ports:
      - "8001:3000"
    networks:
      - monitoring-gamma

  ray-casting:
    image: aidanmackey/ray-casting
    container_name: ray-casting
    restart: unless-stopped
    ports:
      - "3001:8080"
    depends_on:
      - aidan-mackey-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9001:9090"
    volumes:
      - "../data/gamma:/prometheus"
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-gamma
    depends_on:
      - aidan-mackey-net
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"

networks:
  monitoring-gamma:
    external: true
