version: "3.8"

services:
  nextjs:
    build: .
    ports:
      - "443:3000"
      - "80:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

