name: Deploy Website

on:
  push:
    branches:
      - beta
      - gamma
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
    outputs:
      build-path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscal -H 


      - name: Deploy to ${{ github.ref_name }}
        run: |
          ssh -i ~/.ssh/id_rsa user@your.server.com << 'EOF'
            cd /var/www/AidanMackey.net/${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            npm install --production
            pm2 restart myapp   # or systemctl restart nginx, docker compose up, etc.
          EOF

